name: test
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Run tests
        run: |
          npm ci
          npm test

      - name: Upload jest report
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: report
